---
- name: Generate an execution node receptor install bundle
  hosts: localhost
  gather_facts: no
  #vars:
  #  controller_node_hostname: controller
  #  execution_node_hostname: testexec
  #  input_folder: /home/awx/
  #  output_folder: /var/tmp/receptor_install_bundle
  #  signing_temp_path: /var/tmp/

  tasks:
    - name: Validate required parameters
      ansible.builtin.assert:
        that:
          - controller_node_hostname | default("", true) | length > 0
          - execution_node_hostname | default("", true) | length > 0
          - input_folder | default("", true) | length > 0
          - output_folder | default("", true) | length > 0
          - signing_temp_path | default("", true) | length > 0
        quiet: true
        fail_msg: controller_node_hostname, execution_node_hostname, input_folder, output_folder and signing_temp_path must be provided

    - name: Create the relevant paths if they don't exist
      ansible.builtin.file:
        path: "{{ output_folder }}/receptor/tls/ca/"
        state: directory
        mode: '0755'

    - name: Create the relevant paths if they don't exist
      ansible.builtin.file:
        path: "{{ output_folder }}/group_vars/"
        state: directory
        mode: '0755'

    - name: Copy the mesh CA certificate to the output folder
      ansible.builtin.copy:
        src: "{{ input_folder }}/aap/tls/ca.cert"
        dest: "{{ output_folder }}/receptor/tls/ca/mesh-CA.crt"

    - name: Copy the public key for work signing to the output folder
      ansible.builtin.copy:
        src: "{{ input_folder }}/aap/receptor/etc/signing_public.pem"
        dest: "{{ output_folder }}/receptor/work_public_key.pem"


    - name: Generate a private signing key for the receptor
      community.crypto.openssl_privatekey:
        path: "{{ signing_temp_path }}/receptor.key"
        size: 2048
        type: RSA

    - name: Generate a certificate signing request for the receptor
      community.crypto.openssl_csr:
        path: "{{ signing_temp_path }}/receptor.csr"
        privatekey_path: "{{ signing_temp_path }}/receptor.key"
        common_name: "{{ execution_node_hostname }}"
        subject_alt_name:
          - "DNS:{{ execution_node_hostname }}"
          - "otherName:1.3.6.1.4.1.2312.19.1;UTF8:{{ execution_node_hostname }}"
        subject_alt_name_critical: false

    - name: Generate a certificate from the csr for the receptor
      community.crypto.x509_certificate:
        path: "{{ signing_temp_path }}/receptor.crt"
        csr_path: "{{ signing_temp_path }}/receptor.csr"
        ownca_path: "{{ input_folder }}/aap/tls/ca.cert"
        ownca_privatekey_path: "{{ input_folder }}/aap/tls/ca.key"
        provider: ownca

    - name: Copy the receptor key to the output folder
      ansible.builtin.copy:
        src: "{{ signing_temp_path }}/receptor.key"
        dest: "{{ output_folder }}/receptor/tls/receptor.key"

    - name: Copy the receptor cert to the output folder
      ansible.builtin.copy:
        src: "{{ signing_temp_path }}/receptor.crt"
        dest: "{{ output_folder }}/receptor/tls/receptor.crt"

    - name: Generate the install_receptor playbook
      ansible.builtin.template:
        src: templates/install_receptor.j2
        dest: "{{ output_folder }}/install_receptor.yml"
      vars:
        instance:
          node_type: execution

    - name: Generate the inventory file
      ansible.builtin.template:
        src: templates/inventory.j2
        dest: "{{ output_folder }}/inventory.yml"
      vars:
        instance:
          hostname: "{{ execution_node_hostname }}"

    - name: Generate the group_vars file
      ansible.builtin.template:
        src: templates/group_vars.j2
        dest: "{{ output_folder }}/group_vars/all.yml"
      vars:
        instance:
          node_type: execution
        listener_port: false
        peers:
          - address: "{{ controller_node_hostname }}"
            protocol: tls
            port: 27199

    - name: Generate the requirements file
      ansible.builtin.template:
        src: templates/requirements.j2
        dest: "{{ output_folder }}/requirements.yml"
